// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpKUWdCz47wwe6bICt33Ico-osay3_D2g',
    appId: '1:1057148674081:web:617ecfb8ed4832f8adc360',
    messagingSenderId: '1057148674081',
    projectId: 'ansungendoscopy',
    authDomain: 'ansungendoscopy.firebaseapp.com',
    storageBucket: 'ansungendoscopy.appspot.com',
    measurementId: 'G-MGZH3BSMFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwtzdcFnt6o1IuAQuDrHaev8Z92W2fsTI',
    appId: '1:1057148674081:android:074632736d4cac14adc360',
    messagingSenderId: '1057148674081',
    projectId: 'ansungendoscopy',
    storageBucket: 'ansungendoscopy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU2WfVbeC9StcMEjXMNiH7AdkeA1xwfLQ',
    appId: '1:1057148674081:ios:7f653a0b26280199adc360',
    messagingSenderId: '1057148674081',
    projectId: 'ansungendoscopy',
    storageBucket: 'ansungendoscopy.appspot.com',
    iosBundleId: 'com.example.ansungEndo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU2WfVbeC9StcMEjXMNiH7AdkeA1xwfLQ',
    appId: '1:1057148674081:ios:789151f4c5b01f2badc360',
    messagingSenderId: '1057148674081',
    projectId: 'ansungendoscopy',
    storageBucket: 'ansungendoscopy.appspot.com',
    iosBundleId: 'com.example.ansungEndo.RunnerTests',
  );
}
